version: "3"

services:
  zookeeper3:
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    ports:
      - '2181:2181'
    hostname: zookeeper3
    container_name: zookeeper
    networks:
      - cluster_net
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  kafka-2:
    image: docker.io/bitnami/kafka:3.2
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - cluster_net
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://172.16.0.203:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=10000
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper3

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  cluster_net:
    driver: overlay
    external:
      name: cluster-net